# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170905_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='Add a description'),
        ),
    ]
