# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
